class WineData {
  String productImg, productName, color, country, price, description;
  int id, quantity;

  WineData(this.productImg, this.productName, this.color, this.country,
      this.price, this.description, this.id, this.quantity);

  static List<WineData> WineInfo() {
    return [
      WineData("images/wine.png", "San Valentin Garnach 2016", "Red wine",
          "Spain", "12.29", "lorem ipsum", 1, 1),
      WineData("images/wine8.png", "San Valentin Garnach 2016", "Red wine",
          "Spain", "12.29", "lorem ipsum", 2, 1),
      WineData("images/wine2.png", "San Valentin Garnach 2016", "Red wine",
          "Spain", "12.29", "lorem ipsum", 3, 1),
      WineData("images/wine3.png", "San Valentin Garnach 2016", "Red wine",
          "Spain", "12.29", "lorem ipsum", 4, 1),
      WineData("images/wine4.png", "San Valentin Garnach 2016", "Red wine",
          "Spain", "12.29", "lorem ipsum", 5, 1),
      WineData("images/wine5.png", "San Valentin Garnach 2016", "Red wine",
          "Spain", "12.29", "lorem ipsum", 6, 1),
      WineData("images/wine6.png", "San Valentin Garnach 2016", "Red wine",
          "Spain", "12.29", "lorem ipsum", 7, 1),
      WineData("images/wine7.png", "San Valentin Garnach 2016", "Red wine",
          "Spain", "12.29", "lorem ipsum", 8, 1),
      WineData("images/wine8.png", "San Valentin Garnach 2016", "Red wine",
          "Spain", "12.29", "lorem ipsum", 9, 1),
      WineData("images/wine.png", "San Valentin Garnach 2016", "Red wine",
          "Spain", "12.29", "lorem ipsum", 10, 1),
      WineData("images/wine8.png", "San Valentin Garnach 2016", "Red wine",
          "Spain", "12.29", "lorem ipsum", 11, 1),
      WineData("images/wine2.png", "San Valentin Garnach 2016", "Red wine",
          "Spain", "12.29", "lorem ipsum", 12, 1),
      WineData("images/wine3.png", "San Valentin Garnach 2016", "Red wine",
          "Spain", "12.29", "lorem ipsum", 13, 1),
      WineData("images/wine4.png", "San Valentin Garnach 2016", "Red wine",
          "Spain", "12.29", "lorem ipsum", 14, 1),
      WineData("images/wine5.png", "San Valentin Garnach 2016", "Red wine",
          "Spain", "12.29", "lorem ipsum", 15, 1),
      WineData("images/wine6.png", "San Valentin Garnach 2016", "Red wine",
          "Spain", "12.29", "lorem ipsum", 16, 1),
      WineData("images/wine.png", "San Valentin Garnach 2016", "Red wine",
          "Spain", "12.29", "lorem ipsum", 17, 1),
      WineData("images/wine8.png", "San Valentin Garnach 2016", "Red wine",
          "Spain", "12.29", "lorem ipsum", 18, 1),
      WineData("images/wine2.png", "San Valentin Garnach 2016", "Red wine",
          "Spain", "12.29", "lorem ipsum", 19, 1),
      WineData("images/wine3.png", "San Valentin Garnach 2016", "Red wine",
          "Spain", "12.29", "lorem ipsum", 20, 1),
      WineData("images/wine4.png", "San Valentin Garnach 2016", "Red wine",
          "Spain", "12.29", "lorem ipsum", 21, 1),
      WineData("images/wine5.png", "San Valentin Garnach 2016", "Red wine",
          "Spain", "12.29", "lorem ipsum", 22, 1),
      WineData("images/wine6.png", "San Valentin Garnach 2016", "Red wine",
          "Spain", "12.29", "lorem ipsum", 23, 1),
      WineData("images/wine7.png", "San Valentin Garnach 2016", "Red wine",
          "Spain", "12.29", "lorem ipsum", 24, 1),
      WineData("images/wine8.png", "San Valentin Garnach 2016", "Red wine",
          "Spain", "12.29", "lorem ipsum", 25, 1),
      WineData("images/wine.png", "San Valentin Garnach 2016", "Red wine",
          "Spain", "12.29", "lorem ipsum", 26, 1),
      WineData("images/wine8.png", "San Valentin Garnach 2016", "Red wine",
          "Spain", "12.29", "lorem ipsum", 27, 1),
      WineData("images/wine2.png", "San Valentin Garnach 2016", "Red wine",
          "Spain", "12.29", "lorem ipsum", 28, 1),
      WineData("images/wine3.png", "San Valentin Garnach 2016", "Red wine",
          "Spain", "12.29", "lorem ipsum", 29, 1),
      WineData("images/wine4.png", "San Valentin Garnach 2016", "Red wine",
          "Spain", "12.29", "lorem ipsum", 30, 1),
    ];
  }
}
